# !/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 12 15:37:47 2019

@author: python
"""
import sqlalchemy as sa
import os
from typing import TYPE_CHECKING

# Define a version number for the database generated by these writers
# Increment this version number any time a change is made to the schema of the
# asset database
# NOTE: When upgrading this remember to add a downgrade in:
# .asset_db_migrations
ASSET_DB_VERSION = 8
# A frozenset of the names of all tables in the asset db
# NOTE: When modifying this schema, update the ASSET_DB_VERSION value
engine_path = 'mysql+pymysql://root:macpython@localhost:3306/test01'

engine = sa.create_engine(engine_path)

metadata = sa.MetaData(bind=engine)


if TYPE_CHECKING:
    from vnpy.trader.database.database import BaseDatabaseManager

if "VNPY_TESTING" not in os.environ:
    from vnpy.trader.setting import get_settings
    from .initialize import init

    settings = get_settings("database.")
    database_manager: "BaseDatabaseManager" = init(settings=settings)

